# This is a workflow that generates documentation
name: Generating documentation with Doxygen

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the main branch
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "third_party-libs/**"
      - "VGP_Data_Exchange/**"
      - "doxygen-awesome-css/**"
      - "README.MD"
      - "Doxyfile"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "document"
  document:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Print current path
        run: pwd

      - name: Print directory contents
        run: ls

      - name: Setup awesome doxygen
        run: |
          cd doxygen-awesome-css
          git fetch
          git checkout main
          git pull
          cd ..

      - name: Install doxygen
        run: |
          sudo apt-get install wget
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_13_2/doxygen-1.13.2.linux.bin.tar.gz
          tar -xvf doxygen-1.13.2.linux.bin.tar.gz
          cd doxygen-1.13.2
          sudo make install
          cd ..
          rm -rf doxygen-1.13.2
          rm doxygen-1.13.2.linux.bin.tar.gz

      - name: Install graphviz
        run: sudo apt-get install graphviz

      - name: Remove existing files
        run: rm -rf docs

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add ./docs -f
          git commit -m "Updated the documentation" -v
          git push
        continue-on-error: true
